apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      role: webapp
  template:
    metadata:
      labels:
        app: frontend
        role: webapp
    spec:
      containers:
      - name: frontend
        image: pupirka/frontend-app:latest
        ports:
        - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
    role: webapp
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
