apiVersion: v1
kind: Service
metadata:
  name: unified-loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 51.250.26.127  # Ваш статический IP

  ports:
    - name: frontend
      port: 5173           # Внешний порт для фронтенда
      targetPort: 5173   # Порт контейнера фронтенда
    - name: backend
      port: 8000         # Внешний порт для бэкенда
      targetPort: 8000   # Порт контейнера бэкенда
    - name: grafana
      port: 3000
      targetPort: 3000
  selector:
    role: webapp  # Выбирает все  приложения по общей метке

