name: Backend

on:
  push:
    branches: [master]
    #paths:
     # - 'backend/**'
  pull_request:
    branches: [master]
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  BACKEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/backend-app
  TAG: ${{ github.sha }}
  K8S_NAMESPACE: default
  DEPLOYMENT_NAME: backend

jobs:
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Format code with black
        run: |
          pip install black
          black .
#------------------------------------------          
  test-backend:
    needs: build-backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        python-version: [3.9]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV 
          
      - name: Run tests with pytest
        run: pytest --maxfail=1 --disable-warnings --tb=short
#------------------------------------------  
  sonarqube:
    name: SonarQube Scan
    needs: [build-backend, test-backend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Явно указана версия Python
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Добавлен pytest-cov

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Упрощено
          
      - name: Run tests with coverage
        run: |
          #pytest --cov=app --cov-report=xml:coverage.xml tests/
          pytest --cov=app --cov-report=xml:coverage.xml --cov-report=term-missing tests/

      - name: Verify coverage file
        run: |
          ls -la
          cat coverage.xml | head -n 5

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.organization=dzyaka2002
            -Dsonar.qualitygate.wait=true
            -Dsonar.projectKey=dzyaka2002_CRUD_REST_app
            -Dsonar.projectName=CRUD_REST_app
            -Dsonar.sources=backend/app
            -Dsonar.tests=backend/tests
            -Dsonar.exclusions=**/node_modules/**,**/.github/**,**/tests/**,**/venv/**
            -Dsonar.python.coverage.reportPaths=backend/coverage.xml
     
      # 2. Этап проверки Quality Gate
      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          pollingTimeoutSec: 600  # 10 минут ожидания
          retryIntervalSec: 5     # Интервал проверки
#------------------------------------------
  deploy-backend:
    name: Deploy backend
    needs: [build-backend, test-backend, sonarqube]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        working-directory: backend
        run: |
          docker build -t ${{ env.BACKEND_IMAGE }}:latest -t ${{ env.BACKEND_IMAGE }}:${{ env.TAG }} .
          docker push ${{ env.BACKEND_IMAGE }}:latest
          docker push ${{ env.BACKEND_IMAGE }}:${{ env.TAG }}

#------------------------------------------  
  update-k8s:
    needs: deploy-backend
    name: Load new image
    runs-on: ubuntu-latest
    steps:
      - name: Setup YC CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          ~/yandex-cloud/bin/yc config set token ${{ secrets.YC_OAUTH_TOKEN }}
          ~/yandex-cloud/bin/yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          ~/yandex-cloud/bin/yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
          ~/yandex-cloud/bin/yc iam key create --service-account-name k8s --output key.json
          
      - name: Get kubeconfig
        run: ~/yandex-cloud/bin/yc managed-kubernetes cluster get-credentials --id ${{ secrets.YC_K8S_CLUSTER_ID }} --external
      
      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} $(kubectl get deploy ${{ env.DEPLOYMENT_NAME }} -o jsonpath='{.spec.template.spec.containers[0].name}')=${{ env.BACKEND_IMAGE }}:${{ env.TAG }} -n ${{ env.K8S_NAMESPACE }}
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.K8S_NAMESPACE }}
