name: SonarQube Analysis

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend  # Все команды выполняются из папки backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV 
          
      - name: Run tests with coverage
        run: |
          pytest --cov=./ --cov-report=xml:coverage.xml tests/

      - name: Verify coverage file
        run: |
          ls -la coverage.xml
          cat coverage.xml | head -n 5  # Проверяем что файл не пустой

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.qualitygate.wait=true
            -Dsonar.projectKey=${{ github.repository }}
            -Dsonar.projectName=${{ github.repository }}
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/.github/**,**/tests/**,**/venv/**
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.xunit.reportPath=test-results.xml
