name: SonarQube Analysis

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Явно указана версия Python
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Добавлен pytest-cov

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Упрощено
          
      - name: Run tests with coverage
        run: |
          #pytest --cov=app --cov-report=xml:coverage.xml tests/
          pytest --cov=app --cov-report=xml:coverage.xml --cov-report=term-missing tests/

      - name: Verify coverage file
        run: |
          ls -la
          cat coverage.xml | head -n 5

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.organization=dzyaka2002
            -Dsonar.qualitygate.wait=true
            -Dsonar.projectKey=dzyaka2002_CRUD_REST_app
            -Dsonar.projectName=CRUD_REST_app
            -Dsonar.sources=backend/app
            -Dsonar.tests=backend/tests
            -Dsonar.exclusions=**/node_modules/**,**/.github/**,**/tests/**,**/venv/**
            -Dsonar.python.coverage.reportPaths=backend/coverage.xml
