name: SonarQube Analysis

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  SONAR_ORG: "dzyaka2002"
jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Явно указана версия Python
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Добавлен pytest-cov

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV  # Упрощено
          
      - name: Run tests with coverage
        run: |
          pytest --cov-report=xml:coverage.xml tests/  

      - name: Verify coverage file
        run: |
          ls -la coverage.xml
          [ -s coverage.xml ] || exit 1  # Проверка что файл не пустой

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.qualitygate.wait=true
            -Dsonar.projectKey=${{ github.repository }}
            -Dsonar.projectName=${{ github.repository }}
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/.github/**,**/tests/**,**/venv/**
            -Dsonar.python.coverage.reportPaths=coverage.xml
